#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <dirent.h>


int main(int argc, char *argv[])
{

    /** Déclaration des variables*/

    char string[10] = "";
    char PATH[MAX_PATH];
    char FNAME[FILENAME_MAX];
    int Taille_Roms=0;
    unsigned char *Roms_Data;
    unsigned char i=0;
    unsigned char octetActuel=0;
    unsigned short Checksum=0;
    FILE *Roms;

    printf("\n\n");

    printf("\t\t***************************************\n");

    printf("\t\t*     Wonderswan Checksum creator     *\n");

    printf("\t\t***************************************\n");

    printf("\n\n");

    DIR* rep = NULL;
    rep = opendir("\ROMS"); /* Ouverture d'un dossier */


    if (rep == NULL) /* Si le dossier n'a pas pu être ouvert */

        printf("Erreur dossier ROMS introuvable\n");

    else
    {
        printf("Le dossier ROMS a ete ouvert avec succes\n");

        // Calcul du nombre de fichier dans le dossier ROMS

        struct dirent* ent = NULL;
        int nbr = 0;

        while ((ent = readdir(rep)) != NULL)

        {

            if (strcmp(ent->d_name, ".") != 0 && /* Si le fichier lu n'est pas . */

                    strcmp(ent->d_name, "..") != 0) /*  Et n'est pas .. non plus */

                nbr++; /* Alors on incrémente le compteur */

        }
        rewinddir(rep);
        ent = readdir(rep);
        ent = readdir(rep);
        sprintf(string, "%d", nbr); // converstion int2char

        printf("Il y a %ld fichiers dans le dossier ROMS \n",nbr);
        printf("Ecriture du fichier de sortie\n");

        FILE *fp;
        fp=fopen("Swan_chksm.h", "wb");
        fputs("/* Generated by Wonderswan Checksum Creator, do not edit manually */\n",fp);
        fputs("\n",fp);
        fputs("// List of games based on No-Intro Fullset 2013 \n ",fp);
        fputs("\n",fp);
        fputs("const char *WS_Names[",fp);
        fputs(string,fp);
        fputs("]=\n",fp);
        fputs("{\n",fp);

        // Boucle Principale Game Name

        while ((ent = readdir(rep)) != NULL)
        {
            fputc('"',fp);
            fputs(ent->d_name,fp);
            fputc('"',fp);
            fputc(',',fp);
            fputs("\n",fp);
        }
        fputs("};\n",fp);
        fputs("\n",fp);

        rewinddir(rep);
        ent = readdir(rep);
        ent = readdir(rep);

        fputs("const int *WS_Checksum[",fp);
        fputs(string,fp);
        fputs("]=\n",fp);
        fputs("{\n",fp);

        // Boucle Principale Game Checksum

        // On va lire un à un les fichiers du repetoire ROMS

        while ((ent= readdir(rep)) != NULL)
        {
            strcpy(PATH,"\ROMS");
            strcpy(FNAME,PATH);
            strcat(FNAME,"\\");
            strcat(FNAME,ent->d_name);
            Roms = fopen(FNAME,"r");
            fseek(Roms,0,SEEK_END);
            Taille_Roms = ftell(Roms);
            Roms_Data = (char*)malloc(Taille_Roms);
            fseek(Roms,Taille_Roms-2,SEEK_SET); // On repositionne le curseur au checksum

            for(i=0; i<2; i++)
            {
                fread(&octetActuel,1,1,Roms); // On lit un octets
                Roms_Data[i]=octetActuel; // et on l'envoie dans le tableau
            }
            Checksum=((Roms_Data[0] << 8) | (Roms_Data[1]) );

            fputs("0x",fp);
            sprintf(string, "%02hhX",Checksum); // converstion int2char
            fputs(string,fp);
            fputc(',',fp);
            fputs("\n",fp);
            fclose(Roms);
        }

        fputs("};\n",fp);
        fputs("\n",fp);
    }


    // Fin de programme


    return 0;
}


